// SPDX-License-Identifier: Apache-2.0

/**
 * Apex source of the runtime data factory used by generated tests.
 *
 * It reads the org's own schema at runtime, so records are valid in whatever org the tests run
 * in — including required fields that only exist in the org, not in the project:
 *
 * - every createable field that is required (not nillable, not defaulted) gets a value of its
 *   type; picklists use the default or first active value;
 * - required parent records (master-detail) are created once and shared;
 * - callers pass overrides: a literal, `null`, `ANY_VALUE` (any non-blank value) or
 *   `notValue('x')` (a value other than x), as produced by the validation-rule solver.
 */
export function factorySource(className: string): string {
  return `/**
 * Generated by sf-preflight. Test-only data factory: builds valid records from this org's
 * schema at runtime. Safe to regenerate; don't edit by hand.
 */
@IsTest
public class ${className} {
    /** Override value meaning "any non-blank value of the field's type". */
    public static final Object ANY_VALUE = new AnyValue();

    public class AnyValue {
    }

    /** Override value meaning "any value other than this one". */
    public class NotValue {
        public final String value;
        public NotValue(String value) {
            this.value = value;
        }
    }

    public class PreflightException extends Exception {
    }

    public static NotValue notValue(String value) {
        return new NotValue(value);
    }

    private static Integer sequence = 0;
    private static Integer depth = 0;
    private static Map<String, Id> sharedParents = new Map<String, Id>();
    private static Map<String, Schema.SObjectType> globalTypes;
    private static Map<Schema.SObjectField, Map<String, String>> picklistChoices = new Map<Schema.SObjectField, Map<String, String>>();

    private static Schema.SObjectType sobjectTypeFor(String objectName) {
        if (globalTypes == null) {
            globalTypes = Schema.getGlobalDescribe();
        }
        return globalTypes.get(objectName);
    }

    /** Builds records without inserting them. */
    public static List<SObject> build(String objectName, Integer count, Map<String, Object> overrides) {
        Schema.SObjectType sobjectType = sobjectTypeFor(objectName);
        if (sobjectType == null) {
            throw new PreflightException('Unknown object ' + objectName + ' in this org.');
        }
        Map<String, Schema.SObjectField> fields = sobjectType.getDescribe().fields.getMap();
        Map<String, Object> wanted = new Map<String, Object>();
        if (overrides != null) {
            for (String key : overrides.keySet()) {
                if (!fields.containsKey(key.toLowerCase())) {
                    throw new PreflightException('Unknown field ' + objectName + '.' + key + ' in this org.');
                }
                wanted.put(key.toLowerCase(), overrides.get(key));
            }
        }
        // Describe each field once, then fill every record from the plan.
        List<Schema.DescribeFieldResult> plan = new List<Schema.DescribeFieldResult>();
        List<Object> planValues = new List<Object>();
        for (String key : fields.keySet()) {
            Schema.DescribeFieldResult field = fields.get(key).getDescribe();
            Boolean overridden = wanted.containsKey(key);
            Boolean required = !field.isNillable() && !field.isDefaultedOnCreate();
            if (!field.isCreateable() || (!overridden && !required)) {
                continue;
            }
            plan.add(field);
            planValues.add(overridden ? wanted.get(key) : ANY_VALUE);
        }
        List<SObject> records = new List<SObject>();
        for (Integer i = 0; i < count; i++) {
            SObject record = sobjectType.newSObject();
            for (Integer j = 0; j < plan.size(); j++) {
                record.put(plan[j].getName(), resolve(plan[j], planValues[j], null));
            }
            records.add(record);
        }
        return records;
    }

    /** Builds and inserts records. */
    public static List<SObject> create(String objectName, Integer count, Map<String, Object> overrides) {
        List<SObject> records = build(objectName, count, overrides);
        insertRecords(records);
        return records;
    }

    /** Inserts records, explaining a failure in terms of the generated test. */
    public static void insertRecords(List<SObject> records) {
        try {
            insert records;
        } catch (DmlException e) {
            String objectName = records.isEmpty() ? '' : String.valueOf(records[0].getSObjectType());
            throw new PreflightException(
                'Could not create test ' + objectName + ' records: ' + e.getMessage() +
                ' Adjust the overrides in the generated test for this org.'
            );
        }
    }

    public static SObject createOne(String objectName, Map<String, Object> overrides) {
        return create(objectName, 1, overrides)[0];
    }

    /** Sets field values on records (not saved). ANY_VALUE picks a value different from the current one. */
    public static void touch(List<SObject> records, Map<String, Object> values) {
        if (records == null || records.isEmpty() || values == null) {
            return;
        }
        Schema.SObjectType sobjectType = records[0].getSObjectType();
        Map<String, Schema.SObjectField> fields = sobjectType.getDescribe().fields.getMap();
        for (String key : values.keySet()) {
            Schema.SObjectField token = fields.get(key.toLowerCase());
            if (token == null) {
                throw new PreflightException('Unknown field ' + sobjectType + '.' + key + ' in this org.');
            }
            Schema.DescribeFieldResult field = token.getDescribe();
            for (SObject record : records) {
                record.put(field.getName(), resolve(field, values.get(key), record.get(field.getName())));
            }
        }
    }

    private static Object resolve(Schema.DescribeFieldResult field, Object value, Object current) {
        if (value instanceof AnyValue || value instanceof NotValue) {
            return sample(field, value, current);
        }
        return coerce(field, value);
    }

    private static Object coerce(Schema.DescribeFieldResult field, Object value) {
        Boolean numeric = value instanceof Integer || value instanceof Long || value instanceof Decimal || value instanceof Double;
        if (value == null || !numeric) {
            return value;
        }
        Schema.DisplayType fieldType = field.getType();
        if (field.getSoapType() == Schema.SoapType.STRING) {
            return String.valueOf(value);
        }
        Decimal asDecimal = Decimal.valueOf(String.valueOf(value));
        if (fieldType == Schema.DisplayType.INTEGER) {
            return asDecimal.intValue();
        }
        if (fieldType == Schema.DisplayType.LONG) {
            return asDecimal.longValue();
        }
        if (fieldType == Schema.DisplayType.DOUBLE || fieldType == Schema.DisplayType.CURRENCY || fieldType == Schema.DisplayType.PERCENT) {
            return asDecimal;
        }
        return value;
    }

    private static Boolean sameNumber(Object a, Decimal b) {
        if (a == null) {
            return false;
        }
        try {
            return Decimal.valueOf(String.valueOf(a)) == b;
        } catch (TypeException e) {
            return false;
        }
    }

    private static Object sample(Schema.DescribeFieldResult field, Object spec, Object current) {
        sequence++;
        String unique = String.valueOf(sequence);
        String excluded = spec instanceof NotValue ? ((NotValue) spec).value : null;
        Schema.DisplayType fieldType = field.getType();
        if (fieldType == Schema.DisplayType.PICKLIST || fieldType == Schema.DisplayType.MULTIPICKLIST || fieldType == Schema.DisplayType.COMBOBOX) {
            Schema.SObjectField token = field.getSObjectField();
            if (!picklistChoices.containsKey(token)) {
                picklistChoices.put(token, new Map<String, String>());
            }
            Map<String, String> choices = picklistChoices.get(token);
            String cacheKey = String.valueOf(excluded) + '|' + String.valueOf(current);
            if (!choices.containsKey(cacheKey)) {
                choices.put(cacheKey, pickValue(field, excluded, current));
            }
            String choice = choices.get(cacheKey);
            if (choice != null || fieldType != Schema.DisplayType.COMBOBOX) {
                return choice;
            }
            return 'Preflight ' + unique;
        }
        if (fieldType == Schema.DisplayType.REFERENCE) {
            return parentId(field, current);
        }
        if (fieldType == Schema.DisplayType.BOOLEAN) {
            if (current != null) {
                return !((Boolean) current);
            }
            return excluded == null || excluded.toLowerCase() != 'true';
        }
        if (fieldType == Schema.DisplayType.DATE) {
            Date candidate = Date.today();
            return current == candidate ? candidate.addDays(1) : candidate;
        }
        if (fieldType == Schema.DisplayType.DATETIME) {
            Datetime candidate = Datetime.now();
            return current == candidate ? candidate.addDays(1) : candidate;
        }
        if (fieldType == Schema.DisplayType.TIME) {
            Time candidate = Time.newInstance(12, 0, 0, 0);
            return current == candidate ? candidate.addHours(1) : candidate;
        }
        Boolean whole = fieldType == Schema.DisplayType.INTEGER || fieldType == Schema.DisplayType.LONG;
        if (whole || fieldType == Schema.DisplayType.DOUBLE || fieldType == Schema.DisplayType.CURRENCY || fieldType == Schema.DisplayType.PERCENT) {
            // A different value per record (unique and external ID fields), within the field's digits.
            Integer digits = whole ? field.getDigits() : field.getPrecision() - field.getScale();
            Long ceiling = digits > 0 && digits < 10 ? Math.pow(10, digits).longValue() - 1 : 999999999L;
            Long position = sequence;
            Decimal candidate = Math.mod(position, ceiling) + 1;
            for (Integer attempt = 0; attempt < 2 && (sameNumber(current, candidate) || sameNumber(excluded, candidate)); attempt++) {
                candidate = Math.mod(candidate.longValue(), ceiling) + 1;
            }
            if (fieldType == Schema.DisplayType.INTEGER) {
                return candidate.intValue();
            }
            return fieldType == Schema.DisplayType.LONG ? (Object) candidate.longValue() : (Object) candidate;
        }
        if (fieldType == Schema.DisplayType.EMAIL) {
            return 'preflight' + unique + '@example.com';
        }
        if (fieldType == Schema.DisplayType.PHONE) {
            return '555' + String.valueOf(1000000 + sequence);
        }
        if (fieldType == Schema.DisplayType.URL) {
            return 'https://example.com/' + unique;
        }
        if (fieldType == Schema.DisplayType.BASE64) {
            return Blob.valueOf('Preflight ' + unique);
        }
        if (fieldType == Schema.DisplayType.STRING || fieldType == Schema.DisplayType.TEXTAREA || fieldType == Schema.DisplayType.ENCRYPTEDSTRING) {
            String text = 'Preflight ' + unique;
            Integer length = field.getLength();
            return length > 0 && text.length() > length ? text.right(length) : text;
        }
        return null;
    }

    /** The default active value, else the first active one, skipping \`excluded\` and \`current\`. */
    private static String pickValue(Schema.DescribeFieldResult field, String excluded, Object current) {
        String fallback = null;
        for (Schema.PicklistEntry entry : field.getPicklistValues()) {
            String candidate = entry.getValue();
            if (!entry.isActive() || candidate == excluded || (current != null && candidate == String.valueOf(current))) {
                continue;
            }
            if (entry.isDefaultValue()) {
                return candidate;
            }
            if (fallback == null) {
                fallback = candidate;
            }
        }
        return fallback;
    }

    /**
     * One shared parent per parent object, created on first use; the running user for user
     * lookups. Creates another parent when the record already points at the shared one.
     */
    private static Id parentId(Schema.DescribeFieldResult field, Object current) {
        List<Schema.SObjectType> targets = field.getReferenceTo();
        for (Schema.SObjectType parentType : targets) {
            if (parentType == User.SObjectType && current != UserInfo.getUserId()) {
                return UserInfo.getUserId();
            }
        }
        for (Schema.SObjectType parentType : targets) {
            Schema.DescribeSObjectResult parentDescribe = parentType.getDescribe();
            String parentName = parentDescribe.getName();
            Boolean shared = sharedParents.containsKey(parentName);
            if (shared && sharedParents.get(parentName) != current) {
                return sharedParents.get(parentName);
            }
            if (!parentDescribe.isCreateable() || parentType == User.SObjectType) {
                continue;
            }
            if (depth > 5) {
                throw new PreflightException('Parent records nest too deeply at ' + parentName + '.');
            }
            depth++;
            try {
                Id parent = createOne(parentName, null).Id;
                if (!shared) {
                    sharedParents.put(parentName, parent);
                }
                return parent;
            } finally {
                depth--;
            }
        }
        return null;
    }
}
`;
}
